### ISSUE TITLE
Fatiando Community Calls

### ISSUE THREAD

**Issue by leouieda** [fatiando/contributing#17]
Hi @fatiando/contributors, I'm thinking of starting bi-weekly Fatiando Community Calls next month. How about we kick this off Friday 15 of May at 15:00 UTC?

These calls are open to anyone interested in getting involved. We would discuss developments in the various projects and just have a quick chat to get to know each other better. Ideally, I would want to keep the calls to ~40 min.

Let me know if you'd like to attend. If you want to participate but the time doesn't work for you, let me know as well.

I made a calendar for the project here to make it easier to track events: http://calendar.fatiando.org

The meeting notes will be here: https://hackmd.io/@fatiando/community-calls-2020

**Comment by jessepisel** [comment]
This would be a great chance for everyone to meet, Time and date work well for me, so I'll be there.

**Comment by leouieda** [comment]
Meetings have been happening about 1/month. Notes and recordings are on the HackMD link above.
