### ISSUE TITLE
Automatically update files on projects after new commit on contributing repo

### ISSUE THREAD

**Issue by santisoler** [fatiando/contributing#5]
The files inside this repo are maintained here, but they are useful on each projects inside the Fatiando ecosystem. That's where they are ultimately read and has meaning and purpose.
Would be nice to automate the update process of those files -- when a commit is pushed on `contributing`, the changes would be automatically applied to each project.

Two methods come to my mind:
1. Use `git submodule` on the projects' repositories to have the latest version of `contribute` inside them.
2. Use Travis CI to open PRs on each project committing the changes on `contribute:master`.

I don't quite like the first idea, because the submodule has to be manually updated and we cannot link single files (we would need to create symlinks to the submoduled files --  [see this](https://stackoverflow.com/questions/15844542/git-symlink-reference-to-a-file-in-an-external-repository)).

The second approach is way better: the updates should be done manually, but only by merging a few PRs. Although I don't know if Travis CI is capable of opening new PRs on a different repository.
Maybe we will need to access the GitHub API with tools such as [pyGitgub](https://github.com/PyGithub/PyGithub) or [hub](https://github.com/github/hub).

What do you think @leouieda?

**Comment by leouieda** [comment]
+1000 for option 2. That would be the ideal situation. I think we can get `hub` working with a Github token by setting `GITHUB_TOKEN` as an encrypted variable.

**Comment by leouieda** [comment]
Done in #6
