### ISSUE TITLE
Format docstrings with 80 chars

### ISSUE THREAD

**Issue by leouieda** [fatiando/contributing#9]
As pointed out by @prisae earlier, our docstrings are following the Black standard line length but tools like Jupyter format everything at 80 chars. So our docstrings are kind of unreadable in Jupyter and IPython. We **really** need to reformat docstrings to 80 chars again. To this point, we'll need a lot of PRs to all our projects that reformats the docstrings manually (since black won't do it). We should also have a PR on this repo adding this requirement to our CONTRIBUTING.md (it will get propagated to our other repos by the bot).

**Comment by prisae** [comment]
Where did you see the problem appear that this surfaces again?

**Comment by leouieda** [comment]
Everywhere :slightly_smiling_face: Just took this long for this to bubble up to the top of my TODO.

**Comment by prisae** [comment]
Just linking here, for context.

https://github.com/fatiando/verde/issues/177
